version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(name)s : %(message)s"
    timestamp:
        format: "%(asctime)s - %(name)s - %(levelname)s : %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: timestamp
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: INFO
    handlers: [console, info_file_handler]